package org.betterx.betterend.recipe;

import org.betterx.betterend.recipe.builders.InfusionRecipe;
import org.betterx.betterend.registry.EndBlocks;
import org.betterx.betterend.registry.EndItems;

import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Blocks;

public class InfusionRecipes {
    public static void register() {
        InfusionRecipe.create("runed_flavolite", EndBlocks.FLAVOLITE_RUNED)
                      .setPrimaryInput(EndBlocks.FLAVOLITE.polished)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(100)
                      .build();

        InfusionRecipe.create("eternal_crystal", EndItems.ETERNAL_CRYSTAL)
                      .setPrimaryInputAndUnlock(Items.END_CRYSTAL)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, EndItems.ENDER_SHARD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, EndItems.ENDER_SHARD)
                      .setTime(250)
                      .build();

        InfusionRecipe.create("crystalite_helmet", EndItems.CRYSTALITE_HELMET)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.helmet)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(150)
                      .build();
        InfusionRecipe.create("crystalite_chestplate", EndItems.CRYSTALITE_CHESTPLATE)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.chestplate)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(300)
                      .build();
        InfusionRecipe.create("crystalite_leggings", EndItems.CRYSTALITE_LEGGINGS)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.leggings)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(225)
                      .build();
        InfusionRecipe.create("crystalite_boots", EndItems.CRYSTALITE_BOOTS)
                      .setPrimaryInputAndUnlock(EndBlocks.TERMINITE.boots)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(150)
                      .build();

        InfusionRecipe.create("crystalite_elytra", EndItems.CRYSTALITE_ELYTRA)
                      .setPrimaryInputAndUnlock(Items.ELYTRA)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.ENCHANTED_MEMBRANE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(500)
                      .build();

        InfusionRecipe.create("enchanted_petal", EndItems.ENCHANTED_PETAL)
                      .setPrimaryInputAndUnlock(EndItems.HYDRALUX_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(75)
                      .build();
        InfusionRecipe.create("enchanted_membrane", EndItems.ENCHANTED_MEMBRANE)
                      .setPrimaryInputAndUnlock(Items.PHANTOM_MEMBRANE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.CRYSTAL_SHARDS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.CRYSTAL_SHARDS)
                      .setTime(75)
                      .build();

        InfusionRecipe.create(
                              "protection_book",
                              Enchantments.ALL_DAMAGE_PROTECTION, 1
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.TURTLE_HELMET)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create(
                              "fire_protection_book",
                              Enchantments.FIRE_PROTECTION, 1
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.BLAZE_ROD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create(
                              "feather_falling_book",
                              Enchantments.FALL_PROTECTION, 1
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.FEATHER)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create(
                              "blast_protection_book",
                              Enchantments.BLAST_PROTECTION, 1
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.OBSIDIAN)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create(
                              "projectile_protection_book",
                              Enchantments.PROJECTILE_PROTECTION, 1
                      )
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.SCUTE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SHIELD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.SCUTE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("respiration_book", Enchantments.RESPIRATION, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.NAUTILUS_SHELL)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("aqua_affinity_book", Enchantments.AQUA_AFFINITY, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.PRISMARINE_CRYSTALS)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("thorns_book", Enchantments.THORNS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.CACTUS)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("depth_strider_book", Enchantments.DEPTH_STRIDER, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.LILY_PAD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndBlocks.END_LILY_SEED)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.LILY_PAD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("frost_walker_book", Enchantments.FROST_WALKER, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndBlocks.ANCIENT_EMERALD_ICE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("soul_speed_book", Enchantments.SOUL_SPEED, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("swift_sneak_book", Enchantments.SWIFT_SNEAK, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.SCULK_SENSOR)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SCULK_CATALYST)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.SCULK_SENSOR)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.SCULK_VEIN)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.SCULK_VEIN)
                      .setGroup("enchantment")
                      .setTime(500)
                      .build();
        InfusionRecipe.create("sharpness_book", Enchantments.SHARPNESS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.NETHERITE_SCRAP)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("smite_book", Enchantments.SMITE, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.SUNFLOWER)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.GOLD_INGOT)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.SUNFLOWER)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("bane_of_arthropods_book", Enchantments.BANE_OF_ARTHROPODS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.FERMENTED_SPIDER_EYE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.IRON_INGOT)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.FERMENTED_SPIDER_EYE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("knockback_book", Enchantments.KNOCKBACK, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.REDSTONE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Blocks.PISTON)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.REDSTONE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("fire_aspect_book", Enchantments.FIRE_ASPECT, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.MAGMA_CREAM)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("looting_book", Enchantments.MOB_LOOTING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.GOLD_INGOT)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("sweeping_book", Enchantments.SWEEPING_EDGE, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.GOLDEN_SWORD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.IRON_SWORD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.GOLDEN_SWORD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("efficiency_book", Enchantments.BLOCK_EFFICIENCY, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("silk_touch_book", Enchantments.SILK_TOUCH, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Blocks.COBWEB)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Blocks.COBWEB)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
        InfusionRecipe.create("unbreaking_book", Enchantments.UNBREAKING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.DIAMOND)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("fortune_book", Enchantments.BLOCK_FORTUNE, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.RABBIT_FOOT)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("power_book", Enchantments.POWER_ARROWS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.DIAMOND_SWORD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, EndItems.AMBER_GEM)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("punch_book", Enchantments.PUNCH_ARROWS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.POPPED_CHORUS_FRUIT)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.POPPED_CHORUS_FRUIT)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("flame_book", Enchantments.FLAMING_ARROWS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.BLAZE_POWDER)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("infinity_book", Enchantments.INFINITY_ARROWS, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, EndItems.ETERNAL_CRYSTAL)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
        InfusionRecipe.create("luck_of_sea_book", Enchantments.FISHING_LUCK, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.FISHING_ROD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.EMERALD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("lure_book", Enchantments.FISHING_SPEED, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.GOLD_NUGGET)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.FISHING_ROD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.GOLD_NUGGET)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("loyalty_book", Enchantments.LOYALTY, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.ENDER_EYE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.ENDER_EYE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
        InfusionRecipe.create("impaling_book", Enchantments.IMPALING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.PRISMARINE_SHARD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.IRON_SWORD)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.PRISMARINE_SHARD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("riptide_book", Enchantments.RIPTIDE, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.LEAD)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.LEAD)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
        InfusionRecipe.create("channeling_book", Enchantments.CHANNELING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.CHAIN)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.HEART_OF_THE_SEA)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.CHAIN)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
        InfusionRecipe.create("multishot_book", Enchantments.MULTISHOT, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("quick_charge_book", Enchantments.QUICK_CHARGE, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.QUARTZ)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.QUARTZ)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("piercing_book", Enchantments.PIERCING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Items.SPECTRAL_ARROW)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.GLOWSTONE_DUST)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(300)
                      .build();
        InfusionRecipe.create("mending_book", Enchantments.MENDING, 1)
                      .setPrimaryInputAndUnlock(Items.BOOK)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH, EndItems.ENCHANTED_PETAL)
                      .addCatalyst(InfusionRecipe.Catalysts.EAST, Items.EXPERIENCE_BOTTLE)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH, Blocks.ANVIL)
                      .addCatalyst(InfusionRecipe.Catalysts.WEST, Items.EXPERIENCE_BOTTLE)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_EAST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.SOUTH_WEST, Items.LAPIS_LAZULI)
                      .addCatalyst(InfusionRecipe.Catalysts.NORTH_WEST, Items.LAPIS_LAZULI)
                      .setGroup("enchantment")
                      .setTime(375)
                      .build();
    }

}
